Repository glpi-project/java-library-glpi, pull requests merged in 2018-12, with the labels that each got.

#57 Add how to import library
  _posts/static/2018-12-04-how-to-import.md
Labels: documentation

#60 Add installation section in Readme
  README.md
Labels: documentation

#61 Changes in config and scripts files
  .circleci/config.yml
  ci/scripts/ci_github_release.sh
  ci/scripts/ci_push_changes.sh
Labels: ci

#66 Add missing information
  README.md
Labels: documentation

#70 Get Multiple Items
  example/src/main/java/org/glpi/glpiproject/MainActivity.java
  glpi/src/main/java/org/glpi/api/GLPI.java
  glpi/src/main/java/org/glpi/api/Routes.java
  glpi/src/main/java/org/glpi/api/query/GetMultipleItemsQuery.java
Labels: feature

#72 Fix bintray link
  README.md
Labels: documentation
